### ISSUE TITLE
Installing raid too difficult

### ISSUE THREAD

**Issue by deri82** [linuxmint/ubiquity#8]
You need to install mdadm before starting the installer and create raid. After install you need to chroot yourself and install the mdadm on the current install so you can boot with raid on.

I have also had issues with not able to install grub when trying to enable raid.

**Comment by clefebvre** [comment]
I'm sorry. We looked into this and found out dmraid was voluntarily not added in Ubuntu trusty because it created issues (performance mostly) on systems which didn't use raid. I'd recommend chasing the issue upstream with Ubiquity directly so that they can consider it in 16.04 (which we'll base Mint 18 on).
